dist: xenial
language: python
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run -m pytest
after_success:
  - codecov
  
matrix:
  include:
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
