

<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"> 
<meta http-equiv="content-language" content="en-gb">

<meta name="keywords" content="Math,  Maths,  Mathematics,  Numeracy, Starter of the day, Tablesmaster, Shine+Write, Arithmetic, Numbers, Calculate, Thinking Skills">
<meta charset="utf-8"> 
<meta http-equiv="content-language" content="en-gb">
<meta name="description" content="A large collection of free interactive online activity supporting the teaching and learning of Mathematics.">
<meta name="author" content="Transum Mathematics">
<meta name="copyright" content="(C) Transum Mathematics. https://www.Transum.org/Software">
<meta name="distribution" content="Global">
<meta name="robots" content="All">
<meta name="rating" content="General">
<meta name="abstract" content="Free online interactive resources for Mathematics Teachers.">
<meta property="og:title" content="Transum">
<meta property="og:type" content="website">
<meta property="og:description" content="A large collection of free interactive online activity supporting the teaching and learning of Mathematics.">
<meta property="og:url" content="https://www.transum.org">
<meta property="og:site_name" content="Transum">
<meta property="fb:admins" content="1306410124">
<meta property="og:image" content="https://www.transum.org/software/SW/Starter_of_the_day/images/Apple_Transum.png">
<meta name="thumbnail" content="https://www.transum.org/software/SW/Starter_of_the_day/images/Apple_Transum.png">
<link rel="canonical" href="https://www.transum.org">
<meta name="google-site-verification" content="OmGxb0jJtP_SGYca9O6DZkbpnbbMl_TeU__-cFmwbZU" />

<title>Transum</title>


<style type="text/css">
* {
	box-sizing:border-box;
}
html {
	padding:0px;margin:0px;
}
body {
	background-color:white;
	text-align:center;
	padding:0px;margin:0px;
}
h1 img {
	width:529px;
	height:82px;
}
p {
	font-family:"Lucida Sans", "Lucida Sans Regular", "Lucida Grande", "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
	color:#333333;
}
a img{
	border:0px;
}

#ShareThis {
	text-align:center;
	margin:auto;
	margin-top:15px;
	width:1000px;
}

input[name=Enter] {
	background-color:red;
	color:white;
	font-size:18px;
	width:200px;
	height:50px;
	border:3px black solid;
	border-radius: 25px;
	cursor:pointer;
}
#TransumApple {
	width: 142px;
	height: 195px
}
div#BelowTheFold {
	width:730px;
	margin:auto;
}
div#BelowTheFold p{
	margin:10px;
	font-family:"Lucida Sans", "Lucida Sans Regular", "Lucida Grande", "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
	font-size:14px;
	text-align:left;
}

@media(max-width: 500px) {
	h1 {
		margin:1px;
		padding:0px;
	}
	h1 img {
		width: 282px;
		height: 44px;
	}
	div#GoogleSearch {
		position:relative;
		width:300px;
		margin:2px;
		padding:0px;
	}
	div#GoogleSearch input{
		margin-top:1px;
		padding-top:0px;
	}
	p {
		font-size:10px;
	}
	#TransumApple {
		width: 71px;
		height: 98px
	}
	#ShareThis {
		margin-top:5px;
		width:300px;
	}
	input[name=Enter] {
	font-size:14px;
	width:100px;
	height:25px;
	border:2px black solid;
	border-radius: 10px;
	}
	div#BelowTheFold {
		width:320px;
	}
}
</style>

				<!--This code is for the SHAREIT buttons-->
				<script type="text/javascript">var switchTo5x=true;</script>
				<script type="text/javascript" src="https://w.sharethis.com/button/buttons.js"></script>
				<script type="text/javascript">stLight.options({publisher: "ae6209c3-1450-4f3e-a9fa-76ac27b4c418"}); </script>
				<!--End SHAREIT Code -->

</head>

<body>
<style type="text/css">
div#TopBlackBar {
	background-color:#000000;
	margin:0px;
	width:100%;
	height:40px;
	text-align:center;
	padding:10px;
	margin-bottom:40px;
	position:relative;
}
div#TopBlackBar p, div#TopBlackBar a {
	font-family:"Lucida Sans", "Lucida Sans Regular", "Lucida Grande", "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
	font-size:12px;
	color:white;
}
div#TopBlackBar p{
	text-align:left;
	margin-left:10px;
	margin-top:1px;
}
div#TopBlackBar a {
	text-decoration:none;
}
div#CustomSearch {
	position:absolute;
	right:0px;
	top:8px;
	width:400px;
}
#CustomSearch {
	font-size:10px;
}
@media(max-width: 500px) {
	div#TopBlackBar {
		height:auto;
		margin-bottom:4px;
	}
	div#TopBlackBar p{
		margin-bottom:1px;
	}
</style>

<div id="TopBlackBar">
<div id="CookieNotification" style="display:none;">
<p>Cookies are used on this website. 
<input type="button" onclick="LearnMore();" value="Learn More">
<input type="button" onclick="OKGotIt();" value="OK Got It">
</div>
<script type="text/javascript">
var CookieName = 'AcceptCookies';
document.addEventListener('DOMContentLoaded', function(event) { 
	checkCookie();
});

function LearnMore(){
	window.location.href = 'https://www.transum.org/Privacy.asp';
}

function OKGotIt(){
	document.cookie = "username=" + CookieName + "; expires=Wed, 14 Jul 2038 12:00:00 UTC"; 
	var e = document.getElementById('CookieNotification');
	e.style.display =  'none';
}

function checkCookie() {
  var CookiesAll = document.cookie;
  var CookieExists = false;
  if(CookiesAll.indexOf(CookieName)>0){CookieExists = true;}; 
  //console.log('CookieExists: ',CookieExists);
  var e = document.getElementById('CookieNotification');
  
  if (CookieExists) {
    e.style.display =  'none';
  }else{
  	e.style.display =  'block';
  }
} 
</script>

<p>

<a href="https://www.transum.org/Software/FormativeFeedback/LoginOnly.asp" style="font-weight:bold;text-decoration:underline;">Sign In</a> |

<a href="/Starters" id="SOTDlink">Starter Of The Day</a> | 
<a href="/Software/Tablesmaster/Tablesmaster.asp">Tablesmaster</a> | 
<a href="/Software/Fun_Maths/">Fun&nbsp;Maths</a> | <a href="/Software/Maths_Map/">Maths Map</a> | 
 
<a href="/Software/Transum_Topics.asp">Topics</a> | 
<a href="/Software/">More</a></p>

	<div id="CustomSearch">
			<form method="get" action="/Search.asp">
				<input type="text" name="q" placeholder="Search the Transum website" style="width:190px;">
				<input type="submit" value="Search">
			</form>
	</div>



</div>


<h1><img alt="Transum" src="/Software/SW/Starter_of_the_day/Images/Titles/Transum2.png"></h1>


<p>FREE mathematical activities, puzzles, problems, visual aids, investigations and lots more.<br>
   Enter Transum Maths to see how teaching and learning this fascinating subject can be fun.</p>
<p><a href="/Software"><img alt="Transum Mathematics" src="/Software/SW/Starter_of_the_day/Images/Apple2.png" id="TransumApple"></a></p>
<p><input name="Enter" type="button" onclick="javascript:window.location.href='/Software'" value=" ENTER "></p>



<p>We use cookies to personalise ads and to analyse our traffic. We also share information about your use of<br>our site with our advertising and analytics partners. Please refer to our <a href="Privacy.asp">Privacy Policy</a> for more information.</p>

<p>You can <a href="/software/">enter the site</a> by clicking on the apple picture above or any of the other links on this page<br>assuming you accept our policy.</p>



<hr>

<div id="ShareThis">
				<!--See also the javascript code in Head to power these buttons-->
				<span class='st_sharethis_large' displayText='ShareThis'></span>
				<span class='st_googleplus_large' displayText='Google +'></span>
				<span class='st_facebook_large' displayText='Facebook'></span>
				<span class='st_blogger_large' displayText='Blogger'></span>
				<span class='st_twitter_large' displayText='Tweet'></span>
				<span class='st_delicious_large' displayText='Delicious'></span>
				<span class='st_linkedin_large' displayText='LinkedIn'></span>
				<span class='st_edmodo_large' displayText='Edmodo'></span>
				<span class='st_email_large' displayText='Email'></span>
				<span class='st_digg_large' displayText='Digg'></span>
</div>


<div id="BelowTheFold">



<div class="Dontshowforprinting">
	<style>
		.main-page-responsive { width: 320px; height: 50px; }
		@media(min-width: 500px) { .main-page-responsive { width: 468px; height: 60px; } }
		@media(min-width: 800px) { .main-page-responsive { width: 728px; height: 90px; } }
	</style>
	<!-- Main Page Responsive -->
	<ins class="adsbygoogle main-page-responsive"
     	style="display:inline-block"
     	data-ad-client="ca-pub-3448116359683998"
     	data-ad-slot="6356927442"></ins>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>


<p>Transum.org [also at Transum.info and Transum.com] developed as an eclectic mix of free webware featuring online activities to help you with 
			Mathematics. You can read the latest <a href="https://www.transum.org/Press_Release.asp">Press Release</a> or see the <a href="https://www.transum.org/Others.asp">other</a> parts of the site.</p>
	<p>&nbsp;</p>
			
<p style="text-align:center">Contact Us:<br><img alt="Contact Us" src="Software/email.gif" style="width: 272px; height: 32px"></p>


<div class="Dontshowforprinting">
	<!-- Main Page Responsive -->
	<ins class="adsbygoogle main-page-responsive"
     	style="display:inline-block"
     	data-ad-client="ca-pub-3448116359683998"
     	data-ad-slot="6356927442"></ins>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>



<p>&nbsp;</p>
</div>

	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	

<style type="text/css">
div#FooterNew2012 {
	width:100%; height:300px; background-color:#333333; border:3px black solid; margin-top:20px; margin-left:-5px;
	background-image:url('/Software/SW/Starter_of_the_day/Images/Backgrounds/FooterNew2012.gif');
	margin-right: 0px;
	margin-bottom: 0px;
}
div.FooterNew2012_inc_UL {
	padding:0px;
	position:absolute;
	text-align:left;
}
div.FooterNew2012_inc_UL p{
	font-family:Arial, Helvetica, sans-serif;
	color:aliceblue;
	font-size:14px;
	font-weight:normal;
	margin:2px;
}
div.FooterNew2012_inc_UL a{
	color:lightgrey;
	font-size:12px;
	font-family:"Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS", sans-serif;
	text-decoration:none;
}
div.FooterNew2012_inc_UL a:visited, div.FooterNew2012_inc_UL a:active{
	color:lightgrey;
}
div.FooterNew2012_inc_UL ul{
	margin:2px;
}
div.FooterNew2012_inc_UL li{
	list-style:none;
	line-height:16px;
}
div.FooterNew2012_inc_UL input[type=text], div.FooterNew2012_inc_UL input[type=submit] {
	font-size:12px;
}
div#FooterSearch {
	position:absolute;
	border:0px red solid;
	text-align:center;
	width:200px;
	left:510px; 
	top:180px;
	height:20px; 
}
#FooterSearch input{
	font-size:10px;
	color:black;
}

</style>



<div id="FooterNew2012" class="Dontshowforprinting">
	<div style="position:relative; width:800px; margin:auto; height:300px;">
		<img alt="Apple" src="/Software/SW/Starter_of_the_day/Images/Apple2.png" style="width: 142px; height: 195px; position:absolute; top:-30px; right:0px;">
		<div class="FooterNew2012_inc_UL" style="left:0px; top:10px; width:200px;">
			<p>For Students:</p>
			<ul>
	<li><a title="Find an activity for the Maths topic you are studying" href="/Software/Maths_Map/">Maths Map</a></li>
	<li><a title="Activitied to engage your mathematical skills" href="/go/">Go Maths</a></li>
	<li><a title="Mathematical games" href="/Software/Game/">Games</a></li>
	<li><a title="Mathematical puzzles and challenges" href="/Software/Puzzles/">Puzzles</a></li>
	<li><a title="Learn a Times Table in only 5 days!" href="/Tables/Times_Tables.asp">Times Tables</a></li>
	<li><a title="An online multiplication table speed test" href="/Software/Tablesmaster/">TablesMaster</a></li>
	<li><a title="Activities designed to work well on a touch sensitive screen" href="/iPad/Maths.asp">iPad Maths</a></li>
	<li><a title="Your chance to be a Mathematics detective" href="/Software/Investigations/">Investigations</a></li>
	<li><a title="Examination type questions similar to those appearing on GCSE and IB Maths exams." href="/Maths/Exam/">Exam Questions</a></li>
</ul>


			<p>&nbsp;</p>
			
			<a href="https://www.kidsafeseal.com/" target="_blank" ><img alt="Transum.org is a proud supporter of the kidSAFE Seal Program" src="https://www.kidsafeseal.com/supporterlogo/19115794451779121922/transum_supporter.jpg" style="height:59px;width:125px;border:0px;" ></a> 
			
		</div>
		<div class="FooterNew2012_inc_UL" style="left:210px; top:10px; width:200px;">
			<p>For Teachers:</p>
			<ul>
	<li><a title="A Maths Lesson thinking skills starter for each day of the year" href="/Software/SW/Starter_of_the_day/">Starter of the Day</a></li>
	<li><a title="Visual Aids to project on to a whiteboard and write on" href="/Software/SW/index.asp">Shine+Write</a></li>
	<li><a title="Fun mathematical activities for the end of term" href="/Software/Fun_Maths/">Fun Maths</a></li>
	
	<li><a title="Read the latest edition of the Transum Newsletter" href="/Newsletter/">Newsletter</a></li>
	
	<li><a title="Let the Random Student Generator pick a name at random from your class list" href="/Software/RandomStudents/">Random Names</a></li>
	
	
	<li><a title="Some of the videos available on YouTube that may be of use in Mathematics lessons" href="/Software/SW/YouTube/">Maths Videos</a></li>
	
	<!--
	<li><a title="Getting the best out of portable technology for pupils in Mathematics lessons" href="/Software/OnetoOne/">Laptops in Lessons</a></li>	
	-->
	
	<li><a title="Some great ideas for displaying Mathematics in your classroom" href="/Maths/Display/">Maths On Display</a></li>
	
	<li><a title="Our online student information management system and lesson planner" href="/Software/FormativeFeedback/">Class Admin</a></li>
	<li><a id="NC" title="The English National Curriculum for Mathematics with suggested activities" href="/Maths/National_Curriculum/" >Curriculum</a></li>
</ul>
		</div>
		<div class="FooterNew2012_inc_UL" style="left:420px; top:10px; width:200px;">
			<p>For All:</p>
			<ul>

	<li><a title="Sign in or subscribe to Transum" href="/Software/FormativeFeedback/LoginOnly.asp">Sign In</a></li>

	<li><a title="Buy a licence to use Transum at your school" href="/Software/Transum_Buy.asp">Create An Account</a></li>
	<li><a title="Our front door" href="/">Home</a></li>
	<li><a title="What is Transum?" href="/software/Transum_About.asp">About Transum</a></li>
	<li><a title="Find activities to go with the topic you are studying" href="/software/Transum_Topics.asp">Topics</a></li>
	<li><a title="Supporting parents supporting their children in Mathematics" href="/Parents/">Parents</a></li>
	<li><a title="Find out about privacy on the Transum website" href="/Privacy.asp">Privacy Policy</a></li>
	<li><a title="Contact us by email" href="/software/Transum_About.asp">Contact Us</a></li>
	<li><a title="Buy mathematical resources" href="/Software/Transum_Products.asp">Shop</a></li>
</ul>


		</div>
	

	<div id="FooterSearch">
			<form method="get" action="/Search.asp">
				<input type="text" name="q" placeholder="Search Transum" style="width:120px;">
				<input type="submit" value="Search">
			</form>
	</div>
	
	
		<p style="text-align:center;"><a title="Transum" style="font-family:'Courier New', Courier, monospace; color:silver; font-size:18px; font-weight:bold; text-decoration:none; position:absolute; bottom:25px; left:280px;" href="https://www.transum.org/Software">&copy;1997-2019 WWW.TRANSUM.ORG</a></p>
	</div>
</div>



<!-- GOOGLE ANALYTICS START -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1403440-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- GOOGLE ANALYTICS END -->


</body>

</html>
